spring.application.name=catalog

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogdb
spring.datasource.username=catalog
spring.datasource.password=catalog
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=*